'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class PizzeriaEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=PizzeriaEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property DetallesOrden() As DbSet(Of DetalleOrden)
    Public Overridable Property Ordenes() As DbSet(Of Orden)
    Public Overridable Property TiposPizza() As DbSet(Of TipoPizza)

End Class
