'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Orden
    Public Property Id As Integer
    Public Property Numero As Integer
    Public Property NombreCliente As String
    Public Property Fecha As Date
    Public Property DireccionEnvio As String
    Public Property Comentarios As String
    Public Property Estado As Integer
    Public Property IdTipoPizza As Integer
    Public Property Cantidad As Integer

    Public Overridable Property TipoPizza As TipoPizza

End Class
