'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Permiso
    Public Property Id As Integer
    Public Property IdRol As Integer
    Public Property IdAccion As Integer

    Public Overridable Property Accion As Accion
    Public Overridable Property Rol As Rol

End Class
