'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Rol
    Public Property Id As Integer
    Public Property Nombre As String
    Public Property Activo As Boolean
    Public Property EsAdmin As Boolean

    Public Overridable Property Permisos As ICollection(Of Permiso) = New HashSet(Of Permiso)
    Public Overridable Property Usuarios As ICollection(Of Usuario) = New HashSet(Of Usuario)

End Class
