'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TipoPizza
    Public Property Id As Integer
    Public Property Nombre As String
    Public Property CantidadPorciones As Integer
    Public Property Descripcion As String
    Public Property Precio As Decimal
    Public Property Tamanio As String

    Public Overridable Property Ordens As ICollection(Of Orden) = New HashSet(Of Orden)

End Class
